[build]
  # 1. Create the env.txt file securely using the Netlify Environment Variable
  # 2. Download Flutter
  # 3. Build the web app
  command = "echo \"$ENV_CONTENT\" > env.txt && git clone https://github.com/flutter/flutter.git -b stable --depth 1 && ./flutter/bin/flutter build web --release"
  
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200