[build]
  # 1. Download Flutter stable
  # 2. Build the web app using the newly downloaded Flutter engine
  command = "git clone https://github.com/flutter/flutter.git -b stable --depth 1 && ./flutter/bin/flutter build web --release"
  
  # Tell Netlify where the final files are generated
  publish = "build/web"

# Fix the SPA routing / 404 errors
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200