[build]
  command = "echo \"API_URL=$API_URL\" > env.txt && echo \"AGORA_APP_ID=$AGORA_APP_ID\" >> env.txt && rm -rf flutter && git clone https://github.com/flutter/flutter.git -b stable --depth 1 && ./flutter/bin/flutter build web --release"
  
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200